In [18]:


import json
import pandas as pd

# Load dataset
with open("dataset.json", "r", encoding="utf-8") as f: # Adjust the file path as needed
    data = json.load(f)

# Convert to DataFrame
df = pd.DataFrame(data)

df.head()

                                     text          intent entities
0            Rahul ko 500 ka bill bana do  Create_Invoice       []
1         Generate invoice for Mohan 1200  Create_Invoice       []
2          3000 ka maal diya Sharma ji ko  Create_Invoice       []
3                     Bill bana do 800 ka  Create_Invoice       []
4  1200 ka bill bana do Ramesh ke naam pe  Create_Invoice       []

In [ ]:
df.head(10)

                                                 text          intent entities
0                        Rahul ko 500 ka bill bana do  Create_Invoice       []
1                     Generate invoice for Mohan 1200  Create_Invoice       []
2                      3000 ka maal diya Sharma ji ko  Create_Invoice       []
3                                 Bill bana do 800 ka  Create_Invoice       []
4              1200 ka bill bana do Ramesh ke naam pe  Create_Invoice       []
5                  Sohan ko 750 ka invoice bhejna hai  Create_Invoice       []
6       2 hazar ka maal diya tha Amit ko bill bana do  Create_Invoice       []
7                   Invoice bana 450 ka Ankit ke liye  Create_Invoice       []
8   Kal jo 900 ka saman diya tha uska bill generat...  Create_Invoice       []
9      1800 ka bill create kar de Gupta ji ke naam se  Create_Invoice       []
10                 650 ka bill bana aur bhej bhi dena  Create_Invoice       []
11         Mohit ko 3 hazar ka maal gaya invoice bana  Create_Invoice       []
12             2500 ka invoice bana do kal ki date se  Create_Invoice       []
13                  999 ka bill bana do customer Ravi  Create_Invoice       []
14                          500 ka bana do bill Rahul  Create_Invoice       []
15                                bill 1400 ka Suresh  Create_Invoice       []
16                2100 ka maal gaya Sharma ji invoice  Create_Invoice       []
17                         kal 800 diya tha uska bill  Create_Invoice       []
18                       3000 ka bana do uske naam pe  Create_Invoice       []
19             Sharma ji ke naam pe ek naya bill bana  Create_Invoice       []
20      Aaj ka 1450 ka invoice bana do Deepak ke liye  Create_Invoice       []
21           4 packet diya tha Raju ko uska bill bana  Create_Invoice       []
22   Rakesh ko kal 2200 ka saman gaya invoice bana de  Create_Invoice       []
23                    875 ka bill generate karo Manoj  Create_Invoice       []
24             Amit ke liye naya invoice bana 3200 ka  Create_Invoice       []
25               600 ka saman diya tha uska bill bana  Create_Invoice       []
26         Ek invoice bana do 510 ka Rohit ke naam se  Create_Invoice       []
27             1500 ka bill create karo aur save karo  Create_Invoice       []
28  Us customer ke liye 700 ka bill bana jo kal aa...  Create_Invoice       []
29              Invoice create karo Suresh ke naam se  Create_Invoice       []
30                      Pooja ko 1500 ka bill bana do  Create_Invoice       []
31   Lakshmi ke naam pe 2200 ka invoice generate karo  Create_Invoice       []
32     Verma Traders ke liye 5000 ka bill create karo  Create_Invoice       []
33  Maa Durga Traders ko 3200 ka maal gaya invoice...  Create_Invoice       []
34  Ritu Kirana Store ke naam se 1800 ka bill bana do  Create_Invoice       []
35  Ek naya invoice bana do 500 ke liye Rahul ke n...  Create_Invoice       []
36  Rahul ke liye 500 ka invoice generate karo aur...  Create_Invoice       []
37                     500 ka bill Rahul ko bhej dena  Create_Invoice       []
38  Customer Mohan ko 1200 ka invoice bana ke bhej do  Create_Invoice       []
39             Mohan ke naam pe 1,200 ka bill bana do  Create_Invoice       []
40      3000 ka invoice Sharma Traders ke liye banado  Create_Invoice       []
41  Sharma ji ke liye teen hazaar ka bill generate...  Create_Invoice       []
42                   Bhai ek invoice bana 250 ke liye  Create_Invoice       []
43               250 ka bill bana do aur print kar lo  Create_Invoice       []
44  Ramesh ke naam pe 1200 ka naya invoice create ...  Create_Invoice       []
45  Aaj ke date ka 1450 ka invoice Deepak ke liye ...  Create_Invoice       []
46               Kal ka 800 ka invoice banake bhej do  Create_Invoice       []
47       Ek draft invoice bana do 999 ka Ravi ke liye  Create_Invoice       []
48  Invoice bana ke email bhi kar do 1500 ka Pooja ko  Create_Invoice       []
49  Verma Traders ke liye 5000 ka formal invoice g...  Create_Invoice       []

In [20]:
X = df["text"]
y = df["intent"]

print("Number of samples:", len(X))
print("Unique intents:", y.unique())

Number of samples: 515
Unique intents: <ArrowStringArray>
[    'Create_Invoice',         'Add_Credit',     'Record_Payment',
      'Check_Balance',      'Send_Reminder',   'Update_Inventory',
 'View_Sales_Summary']
Length: 7, dtype: str

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_vectorized = vectorizer.fit_transform(X)

print("Feature shape:", X_vectorized.shape)

Feature shape: (515, 590)

In [22]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(class_weight="balanced", max_iter=1000)

model.fit(X_vectorized, y)

print("Model retrained with class balancing.")

Model retrained with class balancing.

In [23]:
# Test sentences
test_sentences = [
    "Ritu ko 2400 ka bill bana do",
    "Gupta Store ke liye 5000 ka invoice generate karo",
    "1800 ka bill create karo Pooja ke naam se",
    "Kal ka 900 ka bill bana do Neha ko",
    "Sharma ji ko 1200 ka invoice bhejna hai",
    "Ritu ko 2400 ka bill bana do",
    "Gupta Store ke liye 5000 ka invoice generate karo",
    "1800 ka bill create karo Pooja ke naam se",
    "Ritu ko 2400 ka bill bana do",
    "Gupta Store ke liye 5000 ka invoice generate karo",
    "1800 ka bill create karo Pooja ke naam se",
    "2000 ka maal diya Rahul ko",
    "900 ka bana do uske liye",
    "Usko 1100 ka saman gaya",
    "700 ka likh do",
    "Sharma ji ko 2500 ka entry kar do"
]

# Convert to vector
test_vector = vectorizer.transform(test_sentences)

# Predict
predictions = model.predict(test_vector)

for sentence, pred in zip(test_sentences, predictions):
    print(f"Sentence: {sentence}")
    print(f"Predicted Intent: {pred}")
    print("-" * 40)

Sentence: Ritu ko 2400 ka bill bana do
Predicted Intent: Create_Invoice
----------------------------------------
Sentence: Gupta Store ke liye 5000 ka invoice generate karo
Predicted Intent: Create_Invoice
----------------------------------------
Sentence: 1800 ka bill create karo Pooja ke naam se
Predicted Intent: Create_Invoice
----------------------------------------
Sentence: Kal ka 900 ka bill bana do Neha ko
Predicted Intent: Create_Invoice
----------------------------------------
Sentence: Sharma ji ko 1200 ka invoice bhejna hai
Predicted Intent: Create_Invoice
----------------------------------------
Sentence: Ritu ko 2400 ka bill bana do
Predicted Intent: Create_Invoice
----------------------------------------
Sentence: Gupta Store ke liye 5000 ka invoice generate karo
Predicted Intent: Create_Invoice
----------------------------------------
Sentence: 1800 ka bill create karo Pooja ke naam se
Predicted Intent: Create_Invoice
----------------------------------------
Sentence: Ritu ko 2400 ka bill bana do
Predicted Intent: Create_Invoice
----------------------------------------
Sentence: Gupta Store ke liye 5000 ka invoice generate karo
Predicted Intent: Create_Invoice
----------------------------------------
Sentence: 1800 ka bill create karo Pooja ke naam se
Predicted Intent: Create_Invoice
----------------------------------------
Sentence: 2000 ka maal diya Rahul ko
Predicted Intent: Create_Invoice
----------------------------------------
Sentence: 900 ka bana do uske liye
Predicted Intent: Create_Invoice
----------------------------------------
Sentence: Usko 1100 ka saman gaya
Predicted Intent: Record_Payment
----------------------------------------
Sentence: 700 ka likh do
Predicted Intent: Add_Credit
----------------------------------------
Sentence: Sharma ji ko 2500 ka entry kar do
Predicted Intent: Add_Credit
----------------------------------------

In [24]:
print(y.value_counts())

intent
Create_Invoice        95
Add_Credit            85
Record_Payment        76
Check_Balance         67
View_Sales_Summary    67
Update_Inventory      66
Send_Reminder         59
Name: count, dtype: int64

In [25]:
import numpy as np

probs = model.predict_proba(test_vector)

for sentence, pred, prob in zip(test_sentences, predictions, probs):
    confidence = np.max(prob)
    print(f"Sentence: {sentence}")
    print(f"Predicted Intent: {pred}")
    print(f"Confidence: {confidence:.2f}")
    print("-" * 40)

Sentence: Ritu ko 2400 ka bill bana do
Predicted Intent: Create_Invoice
Confidence: 0.80
----------------------------------------
Sentence: Gupta Store ke liye 5000 ka invoice generate karo
Predicted Intent: Create_Invoice
Confidence: 0.70
----------------------------------------
Sentence: 1800 ka bill create karo Pooja ke naam se
Predicted Intent: Create_Invoice
Confidence: 0.73
----------------------------------------
Sentence: Kal ka 900 ka bill bana do Neha ko
Predicted Intent: Create_Invoice
Confidence: 0.74
----------------------------------------
Sentence: Sharma ji ko 1200 ka invoice bhejna hai
Predicted Intent: Create_Invoice
Confidence: 0.39
----------------------------------------
Sentence: Ritu ko 2400 ka bill bana do
Predicted Intent: Create_Invoice
Confidence: 0.80
----------------------------------------
Sentence: Gupta Store ke liye 5000 ka invoice generate karo
Predicted Intent: Create_Invoice
Confidence: 0.70
----------------------------------------
Sentence: 1800 ka bill create karo Pooja ke naam se
Predicted Intent: Create_Invoice
Confidence: 0.73
----------------------------------------
Sentence: Ritu ko 2400 ka bill bana do
Predicted Intent: Create_Invoice
Confidence: 0.80
----------------------------------------
Sentence: Gupta Store ke liye 5000 ka invoice generate karo
Predicted Intent: Create_Invoice
Confidence: 0.70
----------------------------------------
Sentence: 1800 ka bill create karo Pooja ke naam se
Predicted Intent: Create_Invoice
Confidence: 0.73
----------------------------------------
Sentence: 2000 ka maal diya Rahul ko
Predicted Intent: Create_Invoice
Confidence: 0.23
----------------------------------------
Sentence: 900 ka bana do uske liye
Predicted Intent: Create_Invoice
Confidence: 0.59
----------------------------------------
Sentence: Usko 1100 ka saman gaya
Predicted Intent: Record_Payment
Confidence: 0.19
----------------------------------------
Sentence: 700 ka likh do
Predicted Intent: Add_Credit
Confidence: 0.47
----------------------------------------
Sentence: Sharma ji ko 2500 ka entry kar do
Predicted Intent: Add_Credit
Confidence: 0.28
----------------------------------------

In [26]:
with open("dataset.json", "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.DataFrame(data)

print(df["intent"].value_counts())

intent
Create_Invoice        95
Add_Credit            85
Record_Payment        76
Check_Balance         67
View_Sales_Summary    67
Update_Inventory      66
Send_Reminder         59
Name: count, dtype: int64

In [27]:
X = df["text"]
y = df["intent"]

vectorizer = TfidfVectorizer()
X_vectorized = vectorizer.fit_transform(X)

model = LogisticRegression(class_weight="balanced", max_iter=1000)
model.fit(X_vectorized, y)

print("3-class model trained successfully.")

3-class model trained successfully.

In [28]:
test_sentences = [
    "1500 ka bill bana do Rahul ke liye",
    "Neha ke udhaar mein add karo",
    "Sharma ji ne 2000 transfer kiya",
    "Lakshmi pe 1200 aur chadha do",
    "Gupta ji ke dukaan se 900 mil gaya",
    "Ritu ko 500 ka invoice bhejna hai",
    "Mohan ne aadha paisa diya",
    "600 aur jod do Sunita ke khate mein",
    "Verma Traders ne 3000 clear kar diya",
    "Khan Enterprises ko 1800 ka bill bana do"
]

test_vector = vectorizer.transform(test_sentences)
predictions = model.predict(test_vector)
probs = model.predict_proba(test_vector)

import numpy as np

for sentence, pred, prob in zip(test_sentences, predictions, probs):
    confidence = np.max(prob)
    print(f"Sentence: {sentence}")
    print(f"Predicted Intent: {pred}")
    print(f"Confidence: {confidence:.2f}")
    print("-" * 40)

Sentence: 1500 ka bill bana do Rahul ke liye
Predicted Intent: Create_Invoice
Confidence: 0.86
----------------------------------------
Sentence: Neha ke udhaar mein add karo
Predicted Intent: Add_Credit
Confidence: 0.68
----------------------------------------
Sentence: Sharma ji ne 2000 transfer kiya
Predicted Intent: Record_Payment
Confidence: 0.73
----------------------------------------
Sentence: Lakshmi pe 1200 aur chadha do
Predicted Intent: Add_Credit
Confidence: 0.67
----------------------------------------
Sentence: Gupta ji ke dukaan se 900 mil gaya
Predicted Intent: Record_Payment
Confidence: 0.42
----------------------------------------
Sentence: Ritu ko 500 ka invoice bhejna hai
Predicted Intent: Create_Invoice
Confidence: 0.39
----------------------------------------
Sentence: Mohan ne aadha paisa diya
Predicted Intent: Record_Payment
Confidence: 0.70
----------------------------------------
Sentence: 600 aur jod do Sunita ke khate mein
Predicted Intent: Add_Credit
Confidence: 0.77
----------------------------------------
Sentence: Verma Traders ne 3000 clear kar diya
Predicted Intent: Record_Payment
Confidence: 0.70
----------------------------------------
Sentence: Khan Enterprises ko 1800 ka bill bana do
Predicted Intent: Create_Invoice
Confidence: 0.63
----------------------------------------

In [29]:
import json
import pandas as pd


with open("dataset.json", "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.DataFrame(data)

print("Total samples:", len(df))
print("\nIntent distribution:")
print(df["intent"].value_counts())

Total samples: 515

Intent distribution:
intent
Create_Invoice        95
Add_Credit            85
Record_Payment        76
Check_Balance         67
View_Sales_Summary    67
Update_Inventory      66
Send_Reminder         59
Name: count, dtype: int64

In [30]:
X = df["text"]
y = df["intent"]

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

vectorizer = TfidfVectorizer()
X_vectorized = vectorizer.fit_transform(X)

model = LogisticRegression(class_weight="balanced", max_iter=1000)
model.fit(X_vectorized, y)

print("4-class model trained successfully.")

4-class model trained successfully.

In [31]:
test_sentences = [
    "Rahul ko 1500 ka bill bana do",
    "Neha ke udhaar mein 700 add karo",
    "Sharma ji ne 2000 transfer kiya",
    "Lakshmi ka balance kitna hai",
    "Gupta ji pe kitna baaki hai",
    "Ritu ko 500 ka invoice bhejna hai",
    "Mohan ne aadha paisa diya",
    "Sunita ke khate mein 600 aur jod do",
    "Verma Traders ne 3000 clear kar diya",
    "Khan Enterprises ka outstanding batao"
]

test_vector = vectorizer.transform(test_sentences)
predictions = model.predict(test_vector)
probs = model.predict_proba(test_vector)

import numpy as np

for sentence, pred, prob in zip(test_sentences, predictions, probs):
    confidence = np.max(prob)
    print(f"Sentence: {sentence}")
    print(f"Predicted Intent: {pred}")
    print(f"Confidence: {confidence:.2f}")
    print("-" * 40)

Sentence: Rahul ko 1500 ka bill bana do
Predicted Intent: Create_Invoice
Confidence: 0.77
----------------------------------------
Sentence: Neha ke udhaar mein 700 add karo
Predicted Intent: Add_Credit
Confidence: 0.64
----------------------------------------
Sentence: Sharma ji ne 2000 transfer kiya
Predicted Intent: Record_Payment
Confidence: 0.73
----------------------------------------
Sentence: Lakshmi ka balance kitna hai
Predicted Intent: Check_Balance
Confidence: 0.87
----------------------------------------
Sentence: Gupta ji pe kitna baaki hai
Predicted Intent: Check_Balance
Confidence: 0.66
----------------------------------------
Sentence: Ritu ko 500 ka invoice bhejna hai
Predicted Intent: Create_Invoice
Confidence: 0.39
----------------------------------------
Sentence: Mohan ne aadha paisa diya
Predicted Intent: Record_Payment
Confidence: 0.70
----------------------------------------
Sentence: Sunita ke khate mein 600 aur jod do
Predicted Intent: Add_Credit
Confidence: 0.77
----------------------------------------
Sentence: Verma Traders ne 3000 clear kar diya
Predicted Intent: Record_Payment
Confidence: 0.70
----------------------------------------
Sentence: Khan Enterprises ka outstanding batao
Predicted Intent: Check_Balance
Confidence: 0.45
----------------------------------------

In [32]:
X = df["text"]
y = df["intent"]

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

vectorizer = TfidfVectorizer()
X_vectorized = vectorizer.fit_transform(X)

model = LogisticRegression(class_weight="balanced", max_iter=1000)
model.fit(X_vectorized, y)

print("7-class model trained successfully.")

7-class model trained successfully.

In [33]:
test_sentences = [
    "Rahul ko 1500 ka bill bana do",
    "Neha ke udhaar mein 700 add karo",
    "Sharma ji ne 2000 transfer kiya",
    "Lakshmi ka balance kitna hai",
    "Gupta ji ko payment reminder bhej do",
    "5 packet Maggi stock mein add karo",
    "Aaj ki total sale kitni hui",
    "Mohan ne aadha paisa diya",
    "Sunita ke khate mein 600 aur jod do",
    "Verma Traders ne 3000 clear kar diya",
    "Khan Enterprises ka outstanding batao",
    "Is mahine ka sale summary dikhao"
]

test_vector = vectorizer.transform(test_sentences)
predictions = model.predict(test_vector)
probs = model.predict_proba(test_vector)

import numpy as np

for sentence, pred, prob in zip(test_sentences, predictions, probs):
    confidence = np.max(prob)
    print(f"Sentence: {sentence}")
    print(f"Predicted Intent: {pred}")
    print(f"Confidence: {confidence:.2f}")
    print("-" * 40)

Sentence: Rahul ko 1500 ka bill bana do
Predicted Intent: Create_Invoice
Confidence: 0.77
----------------------------------------
Sentence: Neha ke udhaar mein 700 add karo
Predicted Intent: Add_Credit
Confidence: 0.64
----------------------------------------
Sentence: Sharma ji ne 2000 transfer kiya
Predicted Intent: Record_Payment
Confidence: 0.73
----------------------------------------
Sentence: Lakshmi ka balance kitna hai
Predicted Intent: Check_Balance
Confidence: 0.87
----------------------------------------
Sentence: Gupta ji ko payment reminder bhej do
Predicted Intent: Send_Reminder
Confidence: 0.77
----------------------------------------
Sentence: 5 packet Maggi stock mein add karo
Predicted Intent: Update_Inventory
Confidence: 0.89
----------------------------------------
Sentence: Aaj ki total sale kitni hui
Predicted Intent: View_Sales_Summary
Confidence: 0.79
----------------------------------------
Sentence: Mohan ne aadha paisa diya
Predicted Intent: Record_Payment
Confidence: 0.70
----------------------------------------
Sentence: Sunita ke khate mein 600 aur jod do
Predicted Intent: Add_Credit
Confidence: 0.77
----------------------------------------
Sentence: Verma Traders ne 3000 clear kar diya
Predicted Intent: Record_Payment
Confidence: 0.70
----------------------------------------
Sentence: Khan Enterprises ka outstanding batao
Predicted Intent: Check_Balance
Confidence: 0.45
----------------------------------------
Sentence: Is mahine ka sale summary dikhao
Predicted Intent: View_Sales_Summary
Confidence: 0.68
----------------------------------------

In [34]:
import joblib

joblib.dump(vectorizer, "data/tfidf_vectorizer.pkl")
joblib.dump(model, "data/intent_classifier.pkl")

print("Model saved successfully")

Model saved successfully